### ISSUE TITLE
2.1.0

### ISSUE THREAD

**Issue by dvorsky** [bornfight/avro-to-typescript#4]
For version 3.0.0 several things are planned:

- [x] Clean up whole package, make it easier to extend (#5)
- [x] Write better documentation (#6)
- [x] Write better tests (#7)
- [x] Include BaseAvroRecord in compiler (#10)
- [x] Write tests for stuff added in this version (#15)
